import pytest


@pytest.mark.parametrize(
    "documenter,object_path,expected_rst",
    [
        (
            "pandera_model",
            "target.basic_model.TestModel",
            [
                "",
                ".. py:pandera_model:: TestModel",
                "   :module: target.basic_model",
                "",
                "   First data model for testing purposes",
                "",
                "",
                "   .. py:class:: TestModel.Config()",
                "      :module: target.basic_model",
                "      :canonical: pandera.api.pandas.model.Config",
                "",
                "",
                "      .. py:attribute:: TestModel.Config.name",
                "         :module: target.basic_model",
                "         :type: Optional[str]",
                "         :value: 'TestModel'",
                "",
                "         name of schema",
                "",
                "",
                "   .. py:pandera_field:: TestModel.field1",
                "      :module: target.basic_model",
                "      :type: int",
                "      :value: 'field1'",
                "      :title: Field 1 Title",
                "",
                "      My field  description",
                "",
                "",
                "      :Constraints:",
                "         - **nullable** = False",
                "         - **unique** = False",
                "         - **coerce** = False",
            ],
        ),
        (
            "pandera_model",
            "target.check_model.TestModel",
            [
                "",
                ".. py:pandera_model:: TestModel",
                "   :module: target.check_model",
                "",
                "   Data model with checks",
                "",
                "",
                "   .. py:class:: TestModel.Config()",
                "      :module: target.check_model",
                "",
                "",
                "      .. py:attribute:: TestModel.Config.coerce",
                "         :module: target.check_model",
                "         :value: True",
                "",
                "",
                "      .. py:attribute:: TestModel.Config.name",
                "         :module: target.check_model",
                "         :value: 'TestModel'",
                "",
                "",
                "      .. py:attribute:: TestModel.Config.strict",
                "         :module: target.check_model",
                "         :value: True",
                "",
                "",
                "   .. py:pandera_check:: TestModel.check_coords_non_null(data_df: ~pandas.core.frame.DataFrame) -> ~pandera.typing.pandas.Series[bool]",
                "      :module: target.check_model",
                "      :classmethod:",
                "",
                "      Longitude and latitude should not be null starting 2017",
                "",
                "",
                "   .. py:pandera_check:: TestModel.check_num_finess_format(num_finess_et: ~pandera.typing.pandas.Series[str]) -> ~pandera.typing.pandas.Series[bool]",
                "      :module: target.check_model",
                "      :classmethod:",
                "",
                "      Finess identifiers are 9 characters wide (alphanumerical)",
                "",
                "      :Validates:",
                "         - :py:obj:`num_finess_et <target.check_model.TestModel.num_finess_et>`",
                "         - :py:obj:`num_finess_ej <target.check_model.TestModel.num_finess_ej>`",
                "",
                "",
                "   .. py:pandera_field:: TestModel.date_export",
                "      :module: target.check_model",
                "      :type: ~pandera.typing.pandas.Series[DataType(datetime64[ns])]",
                "      :value: 'date_export'",
                "      :title: Export date",
                "",
                "      Date of the export, exports are made available on a yearly basis",
                "",
                "",
                "      :Constraints:",
                "         - **nullable** = False",
                "         - **unique** = False",
                "         - **coerce** = True",
                "",
                "   .. py:pandera_field:: TestModel.latitude",
                "      :module: target.check_model",
                "      :type: ~pandera.typing.pandas.Series[float]",
                "      :value: 'latitude'",
                "      :title: Latitude",
                "",
                "      Latitude of the location of the care center(WGS 84) (ex: 48.84512493935407)",
                "",
                "",
                "      :Constraints:",
                "         - **nullable** = True",
                "         - **unique** = False",
                "         - **coerce** = False",
                "      :Validated by:",
                "         - **greater_than_or_equal_to(-90)**",
                "         - **less_than_or_equal_to(90)**",
                "",
                "   .. py:pandera_field:: TestModel.longitude",
                "      :module: target.check_model",
                "      :type: ~pandera.typing.pandas.Series[float]",
                "      :value: 'longitude'",
                "      :title: Longitude",
                "",
                "      Longitude of the location of the care center(WGS 84) (ex: 48.84512493935407)",
                "",
                "",
                "      :Constraints:",
                "         - **nullable** = True",
                "         - **unique** = False",
                "         - **coerce** = False",
                "      :Validated by:",
                "         - **greater_than_or_equal_to(-180)**",
                "         - **less_than_or_equal_to(180)**",
                "",
                "   .. py:pandera_field:: TestModel.num_finess_ej",
                "      :module: target.check_model",
                "      :type: ~pandera.typing.pandas.Series[str]",
                "      :value: 'num_finess_ej'",
                "      :title: Juridic FINESS Identifier",
                "",
                "      Identifider of the juridic entity (ex: 920150059)",
                "",
                "",
                "      :Constraints:",
                "         - **nullable** = False",
                "         - **unique** = False",
                "         - **coerce** = False",
                "      :Validated by:",
                "         - :py:obj:`check_num_finess_format <target.check_model.TestModel.check_num_finess_format>`",
                "",
                "   .. py:pandera_field:: TestModel.num_finess_et",
                "      :module: target.check_model",
                "      :type: ~pandera.typing.pandas.Series[str]",
                "      :value: 'num_finess_et'",
                "      :title: Geographic FINESS Identifier",
                "",
                "      Geographic FINESS Identifier (ex: 920000650)",
                "",
                "",
                "      :Constraints:",
                "         - **nullable** = False",
                "         - **unique** = False",
                "         - **coerce** = False",
                "      :Validated by:",
                "         - :py:obj:`check_num_finess_format <target.check_model.TestModel.check_num_finess_format>`",
            ],
        ),
    ],
)
def test_model(documenter, object_path, expected_rst, autodocument):
    actual = autodocument(
        documenter=documenter,
        object_path=object_path,
        testroot="basic",
    )
    assert actual == expected_rst
